#!/bin/bash
# Author : SunFox
# License :
# Date 04-08-2011
# Simple FluxBox Wallpaper Manager.

###Colors definition :
black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
white='\033[1;37m'

###MAIN Constants
SCRIPT_VERSION="$green v2.0"
SCRIPT_NAME="$green Zure $blue - Simple Wallpaper Manager $SCRIPT_VERSION"
SCRIPT_CONFIG_FILE=$HOME"/.sfune-sh.cfg"

AUTO_TIME=60     #Establecemos el tiempo de wallpaper automatico a 1 minuto.
###Color Function
cecho () {
          #Color-echo function
          #Argument $1 : message.
          #Argument $2 : color.
          NONE=""
          MESSAGE1=${1:-$NONE}
          COLOR1=${2:-$white}
          MESSAGE2=${3:-$NONE}
          COLOR2=${4:-$white}
          echo -e "$COLOR1 $MESSAGE1 $COLOR2 $MESSAGE2"
          return
}
necho () {
          #Color-echo function
          #Argument $1 : message.
          #Argument $2 : color.
          NONE=""
          MESSAGE1=${1:-$NONE}
          COLOR1=${2:-$white}
          MESSAGE2=${3:-$NONE}
          COLOR2=${4:-$white}
          echo -ne "$COLOR1 $MESSAGE1 $COLOR2 $MESSAGE2"
          return
}


###################SfuNe's functions
add_info2cfgfile(){
	necho "$blue ::Wallpaper Dir : "; read DIR_WALL
    echo ":WD:$DIR_WALL" >> SCRIPT_CONFIG_FILE
    cecho "$blue ::$green $SCRIPT_CONFIG_FILE $blue created!"
   }
check_config_file(){
     if [ -e $SCRIPT_CONFIG_FILE ]; then
       cecho "$blue ::Loading $green $SCRIPT_CONFIG_FILE.."
       DIR_WALL=`cat $SCRIPT_CONFIG_FILE | grep ":WD" | cut -d":" -f3`
       if [ "$DIR_WALL" == "" ]; then
         add_info2cfgfile
       fi
     else
       touch $SCRIPT_CONFIG_FILE
       cecho "$blue [$red!!$blue] $green Cfg File $red No found "; 
       cecho "$green ::Generating.."
       add_info2cfgfile
     fi
}
show_help(){
     cecho "$blue set  $green -> $yellow Set Wallpaper"
     cecho "$blue auto $green -> $yellow Auto Wallpaper"
}

##############Zure Functions

set_wallpaper(){
                if [ -e $DIR_WALL ]; then
                  ls $DIR_WALL
                  necho "::Select Keyfile : "; read KEY
                  FILE=`ls $DIR_WALL | grep $KEY`
                  TEMP="$HOME/.fluxbox/startup.tmp"
                  LINE="`cat $HOME/.fluxbox/startup | grep fbsetbg`"
                  while read LIN; do
                    if [ "$LIN" == "$LINE" ]; then
                      echo "fbsetbg -f $DIR_WALL$FILE &" >> $TEMP
                    else
                      echo $LIN >> $TEMP
                    fi
                  done< $HOME/.fluxbox/startup
                  mv $TEMP $HOME/.fluxbox/startup
                  fbsetbg -f $DIR_WALL$FILE
                else
                  cecho "$red Error, directorio no definido"
                fi              
}
auto_wallpaper(){
                 if [ -e $DIR_WALL ]; then
                   while : ;do
                     for I in `ls $DIR_WALL`; do
                       cecho "$blue ::Setting $I"
                       fbsetbg -f $DIR_WALL"$I"
                       TEMP="$HOME/.fluxbox/startup.tmp"
                       LINE="`cat $HOME/.fluxbox/startup | grep fbsetbg`"
                       while read LIN; do
                         if [ "$LIN" == "$LINE" ]; then
                           echo "fbsetbg -f $DIR_WALL$I &" >> $TEMP
                         else
                           echo $LIN >> $TEMP
                         fi
                       done< $HOME/.fluxbox/startup
                       mv $TEMP $HOME/.fluxbox/startup
                       sleep $AUTO_TIME
                     done
                   done
                 else
                   cecho "$red Error, directorio no definido"
               fi     
}
cecho "$SCRIPT_NAME"
#echo -n

check_config_file
if [ "$#" -eq "0" ]; then
  show_help
else
  case $1 in
   "set") set_wallpaper;;
   "auto") auto_wallpaper;;
  esac
fi
